name: hf-image

on:
  workflow_dispatch:
    inputs:
      prompt:
        required: true
      request_id:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: pip install huggingface_hub pillow

      - name: run ai image
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PROMPT: ${{ github.event.inputs.prompt }}
          REQUEST_ID: ${{ github.event.inputs.request_id }}
        run: |
          mkdir -p images
          python <<EOF
          from huggingface_hub import InferenceClient
          import os

          client = InferenceClient(
              provider="fal-ai",
              token=os.environ["HF_TOKEN"],
          )

          image = client.text_to_image(
              os.environ["PROMPT"],
              model="Tongyi-MAI/Z-Image-Turbo",
          )

          path = f"images/{os.environ['REQUEST_ID']}.png"
          image.save(path)
          EOF

      - name: commit response image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images/
          git commit -m "Add AI generated image" || echo "nothing to commit"
          git push
