name: hf-chat

on:
  workflow_dispatch:
    inputs:
      prompt:
        required: true
      request_id:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: pip install huggingface_hub requests

      - name: run ai
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          PROMPT: ${{ github.event.inputs.prompt }}
          REQUEST_ID: ${{ github.event.inputs.request_id }}
        run: |
          python <<EOF
          from huggingface_hub import InferenceClient
          import requests, os

          client = InferenceClient(token=os.environ["HF_TOKEN"])

          completion = client.chat.completions.create(
              model="Qwen/Qwen2.5-7B-Instruct:together",
              messages=[{"role":"user","content":os.environ["PROMPT"]}]
          )

          text = completion.choices[0].message.content

          requests.post(
              "http://5.57.37.122:11434/callback",
              json={
                  "request_id": os.environ["REQUEST_ID"],
                  "response": text
              }
          )
          EOF
