name: pxr

on:
  workflow_dispatch:
    inputs:
      allowed_hosts:
        required: true
        type: string
      port:
        required: true
        type: string

jobs:
  proxy:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          pip install mitmproxy cryptography>=41.0.0 h2>=4.1.0 brotli>=1.1.0 zstandard>=0.22.0

      - run: |
          mkdir ca
          cp store/mitmproxy-ca.pem ca/mitmproxy-ca.pem

      - run: |
          echo "${{ github.event.inputs.allowed_hosts }}" > hosts.txt

      - run: |
          nohup mitmdump --listen-host 0.0.0.0 --listen-port ${{ github.event.inputs.port }} --set confdir=ca > proxy.log 2>&1 &
          sleep 21000
