name: pxr2

on:
  workflow_dispatch:

jobs:
  cert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          pip install mitmproxy cryptography>=41.0.0 h2>=4.1.0 brotli>=1.1.0 zstandard>=0.22.0

      - run: |
          mkdir ca
          mitmdump --set confdir=ca -q &
          sleep 5
          pkill mitmdump || true
          cp ca/mitmproxy-ca-cert.pem ca/mitmproxy-ca.pem

      - uses: actions/upload-artifact@v4
        with:
          name: ca
          path: ca/
